### ISSUE TITLE
Running EAST Argman results through TedEval

### ISSUE THREAD

**Issue by mohammedayub44** [clovaai/TedEval#7]
Hi There,

Thanks for your work on this improved evaluation metrics for text detection. I'm trying out some basic models like EAST on some synthetic data and evaluate it. Looks like EAST out of the box creates QUAD format results i.e. x1,y1,x2,y2,x3,y3,x4,y4 and IC13 ground truth text files are in LTRB format i.e. left,top,right,bottom,"transcription" (zip files from your `gt` folder).

Can I still use the `script.py` to give one format for ground truth and another for submission files. ? 

I tried changing `LTRB=True` by default so it reads ground truth correctly but throws an error in my submission files saying format was incorrect and gave `index out of range` error. I know this is because I have 8 points.
Where else do I need to make the changes so, it treats my submission file with 8 points(QUAD), keeping ground truth as LTRB?

Also, open to any other suggestions, like if there is a way to convert my QUAD to LTRB to match with ground truth format. 

Appreciate any help !

Mohammed Ayub

**Comment by mohammedayub44** [comment]
I partially figured it out, let me know if the following changes are correct :

I keep default param `'LTRB':True,`  (L27)

In validate_data() set `evaluationParams['LTRB']` to `False` (L54) - 

```python
rrc_evaluation_funcs.validate_lines_in_file(k,subm[k],evaluationParams['CRLF'],False,evaluationParams['TRANSCRIPTION'],evaluationParams['CONFIDENCES'])
```
 
In evaluate_method() set `evaluationParams['LTRB']` to `False` (L355) - 

```python
pointsList,confidencesList,_ = rrc_evaluation_funcs.get_tl_line_values_from_file_contents(detFile,evaluationParams['CRLF'],False,evaluationParams['TRANSCRIPTION'],evaluationParams['CONFIDENCES'])
```

Additionally had to hardcode `evaluationParams['LTRB']` in this block for if-else to work correctly. For some reason it was still evaluating to `True` instead of `False` and giveing error calling the wrong function (L353-363) -

```python
        for n in range(len(pointsList)):
                evaluationParams['LTRB'] = False
                points = pointsList[n]
                
                if evaluationParams['LTRB']:
                    detRect = Rectangle(*points)
                    detPol = rectangle_to_polygon(detRect)
                    points = polygon_to_points(detPol)
                else:
                    detPol = polygon_from_points(points)                    
                detPols.append(detPol)
                detPolPoints.append(points)
                evaluationParams['LTRB'] = True
```



Thanks !

**Comment by chaeyoung-lee** [comment]
Hello @mohammedayub44 

Thank you for pointing out this issue. Please pull the latest commit 7f807b4 and edit `default_evaluation_params()` in `script.py`. Since your GT file is in LTRB format and result file is in QUAD format, please use
```python
'GT_LTRB': True,
'DET_LTRB': False
```
This will do to run the evaluation script on your data. If this resolves your problem, please close this issue. Thank you!

For a bit more explanation, the main evaluation logic does not care whether the input file (GT or result) is in LTRB or QUAD. The comparison between the GT and the prediction occurs at a polygon level, regardless of the format of each submission. The part of the code you found (L353-363 from your comment) is where detection result, if in LTRB format, are modified to polygons. The same thing happens to the GT data. The previous code, however, assumed that the GT and the result file are in the same format and thus had only one parameter to control the format. In the newest commit 7f807b4, we take two format parameters, one for the GT and one for the result file.

**Comment by mohammedayub44** [comment]
@chaeyoung-lee  That works smooth. Thanks.
